"""
=====================================================================================
文件：07_媒体.py
对应课案章节：Streamlit → 媒体
本节知识点（课案表格里的 3 个组件，全部覆盖）：
  1. st.image   显示图片（支持：本地文件路径 / PIL.Image 对象 / numpy 数组 / URL）
  2. st.audio   播放音频
  3. st.video   播放视频
额外补充：
  4. st.image 的 caption / width / use_column_width 等参数
  5. 多图并排与网格展示
  6. 用 Pillow 现场生成图片（本文件的图片就是这么来的）

★ 本文件的一个重要约定：不引用任何不存在的文件。
  课案里的 st.image("photo.png") / st.video("video.mp4") 需要你自己准备素材。
  本项目【不联网、不下载素材】，所以：
    · 图片：用 Pillow（PIL）在现场生成一张真实的 PNG 存到磁盘，再 st.image 展示；
    · 音频：用 Python 标准库 wave + numpy 现场合成一段正弦波 WAV，再 st.audio 播放；
    · 视频：本环境没有可用的视频生成方式，因此只提供【完整注释说明】用法，
            不做任何运行时读取（这样永远不会因为文件不存在而报错）。

运行方式：
    & 'F:\\ProGram\\Python_Base\\.venv\\Scripts\\python.exe' -m streamlit run `
        'F:\\ProGram\\Python_Base\\Front_End\\04_Streamlit\\07_媒体.py' `
        --server.headless true --server.port 8607 --browser.gatherUsageStats false
=====================================================================================
"""

import math
import wave
from pathlib import Path

import numpy as np
import streamlit as st
from PIL import Image, ImageDraw, ImageFont

# set_page_config 必须是第一个 Streamlit 调用
st.set_page_config(page_title="07 媒体", page_icon="🖼️", layout="wide")

# ---------------------------------------------------------------------------
# 素材目录：用 pathlib 基于【本文件所在目录】计算，不依赖当前工作目录
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent
MEDIA_DIR = BASE_DIR / "_media_output"
MEDIA_DIR.mkdir(parents=True, exist_ok=True)   # 不存在就自动创建

IMAGE_PATH = MEDIA_DIR / "generated_demo.png"
CHART_IMAGE_PATH = MEDIA_DIR / "generated_chart.png"
AUDIO_PATH = MEDIA_DIR / "generated_tone.wav"


# =============================================================================
# 一、用 Pillow 现场生成图片
# -----------------------------------------------------------------------------
# 为什么要生成而不是"找一张图"？
#   因为本项目约定不联网、不下载素材。用代码生成图片有三个好处：
#   ① 完全离线可复现；② 演示了 Pillow 这个常见的图像处理库；
#   ③ st.image 支持直接吃 PIL.Image 对象，正好一起演示。
# =============================================================================
def create_demo_image() -> Image.Image:
    """画一张带渐变背景、图形和文字的示例图片，返回 PIL.Image 对象。"""
    width, height = 640, 400
    img = Image.new("RGB", (width, height), (255, 255, 255))
    draw = ImageDraw.Draw(img)

    # ① 背景：自上而下的线性渐变（逐行画横线）
    for y in range(height):
        t = y / height
        r = int(79 + (168 - 79) * t)      # 从 #4f46e5 渐变到 #a855f7
        g = int(70 + (85 - 70) * t)
        b = int(229 + (247 - 229) * t)
        draw.line([(0, y), (width, y)], fill=(r, g, b))

    # ② 画几个半透明的圆（Pillow 的 RGB 模式没有 alpha，用叠加亮度的方式模拟）
    for i, radius in enumerate((90, 60, 35)):
        cx = 120 + i * 200
        cy = 150
        shade = 255 - i * 30
        draw.ellipse(
            [cx - radius, cy - radius, cx + radius, cy + radius],
            fill=(shade, shade, 255),
            outline=(255, 255, 255),
            width=3,
        )

    # ③ 画一个圆角矩形按钮
    draw.rounded_rectangle([60, 270, 580, 340], radius=16, fill=(255, 255, 255))

    # ④ 写文字。优先用一个确定存在的字体，找不到就退回 Pillow 的默认位图字体，
    #    这样在【任何】机器上都不会因为"字体文件不存在"而报错。
    title = "Pillow 现场生成的示例图片"
    subtitle = "640 x 400  ·  RGB  ·  保存为 PNG"
    font_title = None
    font_sub = None
    for candidate in (
        r"C:\Windows\Fonts\msyh.ttc",      # 微软雅黑
        r"C:\Windows\Fonts\simhei.ttf",    # 黑体
        r"C:\Windows\Fonts\arial.ttf",
    ):
        if Path(candidate).exists():
            try:
                font_title = ImageFont.truetype(candidate, 28)
                font_sub = ImageFont.truetype(candidate, 18)
                break
            except OSError:
                # 字体文件存在但解析失败，继续尝试下一个
                continue

    if font_title is None:
        # 一个字体都没找到，用 Pillow 内置的默认字体（不支持中文，所以写英文）
        title = "Image generated by Pillow"
        subtitle = "640 x 400  |  RGB  |  saved as PNG"
        font_title = ImageFont.load_default()
        font_sub = ImageFont.load_default()

    # anchor="mm" 表示以文字中心点定位，方便居中
    draw.text((width // 2, 150), title, fill=(255, 255, 255), font=font_title, anchor="mm")
    draw.text((width // 2, 305), subtitle, fill=(79, 70, 229), font=font_sub, anchor="mm")

    return img


def create_chart_image() -> Image.Image:
    """
    用 Pillow 的绘图 API 手绘一张柱状图。

    为什么要「手绘」而不是用 matplotlib？
    因为这个函数的目的是演示 **Pillow 本身能画什么**（`ImageDraw` 的
    line / rectangle / ellipse / text），而不是演示画图表 ——
    真正要画图表请用 `05_图表.py` 里的 `st.pyplot(fig)`（matplotlib）
    或 `st.bar_chart`，那些才是专业工具。

    另外这也能说明一个重要事实：**Streamlit 的 `st.image` 接受"任何 PIL.Image 对象"**，
    所以你可以用 Pillow 在运行时生成/加工图片（加水印、裁剪、拼图、生成占位图），
    完全不需要提前准备素材文件。
    """
    width, height = 640, 360
    img = Image.new("RGB", (width, height), (255, 255, 255))
    draw = ImageDraw.Draw(img)

    # 坐标轴
    left, top, right, bottom = 70, 40, 600, 300
    draw.line([(left, bottom), (right, bottom)], fill=(120, 120, 120), width=2)   # x 轴
    draw.line([(left, top), (left, bottom)], fill=(120, 120, 120), width=2)       # y 轴

    # 数据（6 个月的销售额）
    labels = ["1月", "2月", "3月", "4月", "5月", "6月"]
    values = [120, 180, 150, 220, 260, 300]
    max_value = max(values)
    plot_height = bottom - top - 20
    bar_width = (right - left - 40) // len(values) - 12

    for i, (label, value) in enumerate(zip(labels, values)):
        x0 = left + 20 + i * (bar_width + 12)
        bar_height = int(plot_height * value / max_value)
        y0 = bottom - bar_height
        # 柱体
        draw.rectangle([x0, y0, x0 + bar_width, bottom - 1], fill=(79, 70, 229))
        # 数值标注
        draw.text((x0 + bar_width // 2, y0 - 12), str(value), fill=(60, 60, 60), anchor="mm")
        # 月份标签
        draw.text((x0 + bar_width // 2, bottom + 18), label, fill=(90, 90, 90), anchor="mm")

    draw.text((width // 2, 18), "月度销售额（万元）— 用 Pillow 手绘", fill=(40, 40, 40), anchor="mm")
    return img


# =============================================================================
# 二、用标准库 wave + numpy 现场合成一段音频
# =============================================================================
def create_wav_file(path: Path, seconds: float = 2.0, sample_rate: int = 22050) -> Path:
    """
    生成一段可以播放的 WAV 音频文件（正弦波 + 淡入淡出，避免爆音）。

    参数：
        path        输出文件路径
        seconds     时长（秒）
        sample_rate 采样率（Hz）。22050 是常见的语音/提示音采样率。

    原理：WAV 就是「采样点序列 + 头部描述」。
          wave 模块负责写头部，我们只需要把每个采样点的幅度算出来写进去。
    """
    total_samples = int(seconds * sample_rate)
    # 用 numpy 一次性算出所有采样点，比 Python 循环快得多
    t = np.linspace(0, seconds, total_samples, endpoint=False)

    # 三个音叠加：A4(440Hz) 主音 + 五度音 + 八度音，听起来像一个"提示音"
    wave_data = (
        0.6 * np.sin(2 * math.pi * 440.0 * t)
        + 0.25 * np.sin(2 * math.pi * 660.0 * t)
        + 0.15 * np.sin(2 * math.pi * 880.0 * t)
    )

    # 淡入淡出包络：前 10% 渐强，后 20% 渐弱，避免开头/结尾的"啪"声
    envelope = np.ones(total_samples)
    fade_in = int(total_samples * 0.10)
    fade_out = int(total_samples * 0.20)
    envelope[:fade_in] = np.linspace(0.0, 1.0, fade_in)
    envelope[-fade_out:] = np.linspace(1.0, 0.0, fade_out)

    samples = wave_data * envelope
    # 归一化到 int16 的范围（-32768 ~ 32767）
    pcm = (samples * 32767 * 0.8).astype(np.int16)

    # 用 wave 模块写文件：1 声道、2 字节/采样、采样率 sample_rate。
    # pcm 是 numpy 的 int16 数组，tobytes() 得到的正是 WAV 需要的
    # 「小端序、有符号 16 位整数」字节流，所以不需要额外用 struct 打包。
    with wave.open(str(path), "wb") as wav_file:
        wav_file.setnchannels(1)          # 单声道
        wav_file.setsampwidth(2)          # 每个采样 2 字节 = 16 位
        wav_file.setframerate(sample_rate)
        wav_file.writeframes(pcm.tobytes())

    return path


# =============================================================================
# 页面正文
# =============================================================================
st.title("07 媒体组件")
st.caption("对应课案：Streamlit → 媒体")

st.markdown(
    """
| 组件 | 代码 | 作用 |
|---|---|---|
| 图片 | `st.image("img.png", caption="说明")` | 显示图片（本地文件 / PIL 对象 / numpy 数组 / URL） |
| 音频 | `st.audio("song.mp3")` | 播放音频 |
| 视频 | `st.video("video.mp4")` | 播放视频 |
"""
)

st.info(
    "**本文件的约定：绝不引用不存在的文件。**\n\n"
    "图片是用 **Pillow 现场生成的**，音频是用 Python 标准库 **wave 现场合成的**，"
    "视频只做文字说明（本环境没有可用的视频生成方式）。"
    "所以本文件在任何机器上运行都不会出现「文件找不到」的错误。"
)

st.divider()

# ---------------------------------------------------------------------------
# 一、st.image
# ---------------------------------------------------------------------------
st.header("一、st.image 显示图片")

st.subheader("1）四种可接受的输入")

st.markdown(
    """
`st.image(image, caption=None, width=..., use_container_width=None)`

| 传入类型 | 说明 |
|---|---|
| **字符串路径** | 本地文件路径。**必须存在**，否则报错 |
| **URL 字符串** | 网络图片地址（需要联网） |
| **PIL.Image 对象** | 用 Pillow 打开或生成的图片对象 |
| **numpy 数组** | 形状为 (高, 宽) 或 (高, 宽, 3/4) 的数组，常用于处理科学计算图像 |

**参数说明：**

| 参数 | 作用 |
|---|---|
| `caption` | 图片下方的说明文字（可为每张图单独写，传列表） |
| `width` | 宽度。传数字 = 像素；`"stretch"` = 撑满容器宽度；`"content"` = 原始宽度 |
| `use_container_width` | **已弃用**，请改用 `width="stretch"` |
| `channels` | numpy 数组的通道顺序，`"RGB"`（默认）或 `"BGR"` |
| `output_format` | 输出格式，`"auto"` / `"PNG"` / `"JPEG"` / `"WEBP"` |
"""
)

st.subheader("2）本文件生成的图片（先存成 PNG 文件，再当路径用）")

# 只在文件不存在时生成 —— 避免每次脚本重跑都重新画一遍（重跑很频繁！）
if not IMAGE_PATH.exists():
    create_demo_image().save(IMAGE_PATH, "PNG")

if not CHART_IMAGE_PATH.exists():
    create_chart_image().save(CHART_IMAGE_PATH, "PNG")

st.code(
    '''from pathlib import Path
from PIL import Image

# ① 用 Pillow 生成图片并保存成真实文件
img = create_demo_image()          # 返回 PIL.Image.Image 对象
img.save(IMAGE_PATH, "PNG")

# ② 方式 A：把「文件路径」交给 st.image
st.image(str(IMAGE_PATH), caption="从本地 PNG 文件读取", width=420)

# ③ 方式 B：把「PIL.Image 对象」直接交给 st.image（不用先存盘！）
st.image(img, caption="直接传 PIL.Image 对象", width=420)''',
    language="python",
)

img_obj = Image.open(IMAGE_PATH)

col_img1, col_img2 = st.columns(2)
with col_img1:
    st.caption("方式 A：传文件路径（字符串）")
    st.image(str(IMAGE_PATH), caption="从本地 PNG 文件读取", width="stretch")
with col_img2:
    st.caption("方式 B：直接传 PIL.Image 对象")
    st.image(img_obj, caption="直接传 PIL.Image 对象", width="stretch")

st.subheader("3）传 numpy 数组")
st.markdown(
    """
如果你用 OpenCV / skimage 处理图像，拿到的通常是 numpy 数组，
`st.image` 也能直接显示（形状 `(高, 宽, 3)`，且值域应为 `uint8` 的 0~255）。
"""
)
st.code(
    '''arr = np.array(img_obj)              # PIL → numpy，形状 (400, 640, 3)
st.image(arr, caption="numpy 数组", width=300)

# 取红色通道（形状变成 (400, 640)）也能显示，会渲染成灰度图
st.image(arr[:, :, 0], caption="红色通道", width=300)''',
    language="python",
)

arr = np.array(img_obj)
col_arr1, col_arr2 = st.columns(2)
with col_arr1:
    st.caption(f"numpy 数组，形状 {arr.shape}")
    st.image(arr, caption="numpy 数组", width="stretch")
with col_arr2:
    st.caption("取红色通道（二维数组 → 灰度图）")
    # 二维数组会被渲染成灰度图
    st.image(arr[:, :, 0], caption="红色通道", width="stretch")

st.subheader("4）多图并排 / 网格")
st.code(
    '''# 用 st.columns 把页面切成 3 列，每列放一张图
cols = st.columns(3)
for col, path in zip(cols, [IMAGE_PATH, CHART_IMAGE_PATH, IMAGE_PATH]):
    with col:
        st.image(str(path), width="stretch")

# 一次传一个列表给 st.image，它会自动纵向排列
st.image([str(IMAGE_PATH), str(CHART_IMAGE_PATH)], caption=["图一", "图二"], width=280)''',
    language="python",
)

grid_cols = st.columns(3)
for col, (path, cap) in zip(
    grid_cols,
    [(IMAGE_PATH, "生成的示例图"), (CHART_IMAGE_PATH, "Pillow 手绘柱状图"), (IMAGE_PATH, "重复一张")],
):
    with col:
        st.image(str(path), caption=cap, width="stretch")

st.markdown("**一次传列表 + caption 列表：**")
st.image(
    [str(IMAGE_PATH), str(CHART_IMAGE_PATH)],
    caption=["图一：Pillow 生成的装饰图", "图二：Pillow 手绘的柱状图"],
    width=260,
)

st.divider()

# ---------------------------------------------------------------------------
# 二、st.audio
# ---------------------------------------------------------------------------
st.header("二、st.audio 播放音频")

st.markdown(
    """
`st.audio(data, format="audio/wav", start_time=0, end_time=None, loop=False, autoplay=False)`

| 参数 | 作用 |
|---|---|
| `data` | 可以是：文件路径、URL、**字节串 bytes**、numpy 数组 |
| `format` | MIME 类型，如 `"audio/wav"` / `"audio/mp3"` / `"audio/ogg"` |
| `start_time` / `end_time` | 只播放音频的某一段（单位：秒） |
| `loop` | 循环播放 |
| `autoplay` | 自动播放（**浏览器通常会拦截自动播放**，需要用户先与页面交互） |
| `sample_rate` | 当 `data` 是 numpy 数组时，必须指定采样率 |
"""
)

st.subheader("本文件现场合成的 WAV（可以直接点播放）")

if not AUDIO_PATH.exists():
    create_wav_file(AUDIO_PATH, seconds=2.0, sample_rate=22050)

st.code(
    '''import wave, math
import numpy as np

# 用 numpy 算出正弦波的采样点
t = np.linspace(0, 2.0, 44100, endpoint=False)      # 2 秒
samples = np.sin(2 * math.pi * 440.0 * t)           # 440Hz = 标准音 A4
pcm = (samples * 32767 * 0.8).astype(np.int16)      # 转成 16 位整数

# 用标准库 wave 写出 WAV 文件
with wave.open(str(path), "wb") as f:
    f.setnchannels(1)          # 单声道
    f.setsampwidth(2)          # 16 位
    f.setframerate(22050)      # 采样率
    f.writeframes(pcm.tobytes())

# 交给 st.audio 播放
st.audio(str(path), format="audio/wav")''',
    language="python",
)

col_audio, col_audio_info = st.columns([2, 1])
with col_audio:
    st.audio(str(AUDIO_PATH), format="audio/wav")
    st.caption(
        "这是用正弦波合成的一段 2 秒提示音（A4 440Hz + 五度 + 八度），"
        "带淡入淡出，所以不会有爆音。"
    )
with col_audio_info:
    st.metric("时长", "2.0 秒")
    st.metric("采样率", "22050 Hz")
    st.metric("声道", "单声道")
    st.caption(f"文件大小：{AUDIO_PATH.stat().st_size:,} 字节")

st.subheader("其它三种传参方式")
st.code(
    '''# ① 传字节串（比如从数据库或网络拿到的音频二进制）
with open("song.mp3", "rb") as f:
    audio_bytes = f.read()
st.audio(audio_bytes, format="audio/mp3")

# ② 直接传 numpy 数组（必须指定 sample_rate）
st.audio(samples, sample_rate=22050)     # samples 是 -1~1 的浮点数组

# ③ 传 URL（需要联网）
st.audio("https://example.com/song.mp3")

# ④ 只播放第 5 秒到第 10 秒
st.audio("song.mp3", start_time=5, end_time=10)''',
    language="python",
)

# 演示"传 numpy 数组"这条路径（用真实数据，不引用任何外部文件）
st.caption("下面这个是直接把 numpy 数组交给 st.audio（不经过磁盘文件）：")
demo_samples = np.sin(2 * math.pi * 330.0 * np.linspace(0, 1.0, 22050, endpoint=False))
st.audio(demo_samples * 0.8, sample_rate=22050)

st.divider()

# ---------------------------------------------------------------------------
# 三、st.video
# ---------------------------------------------------------------------------
st.header("三、st.video 播放视频")

st.markdown(
    """
`st.video(data, format="video/mp4", start_time=0, end_time=None, loop=False,
autoplay=False, muted=False, subtitles=None)`

| 参数 | 作用 |
|---|---|
| `data` | 文件路径 / URL / **字节串 bytes** |
| `format` | MIME 类型，如 `"video/mp4"` / `"video/webm"` |
| `start_time` | 从第几秒开始播（做"跳到重点片段"很方便） |
| `loop` / `autoplay` / `muted` | 循环 / 自动播放 / 静音（`autoplay` 通常需要配合 `muted=True`） |
| `subtitles` | 字幕文件（`.vtt`）路径 |
"""
)

st.warning(
    "**本节只做文字说明，不在运行时读取任何视频文件。**\n\n"
    "原课案的示例是 `st.video(\"https://www.w3schools.com/html/mov_bbb.mp4\")`，"
    "它需要联网；本项目不保证网络，也不下载素材，因此这里仅说明用法 —— "
    "这样本文件在任何环境下都不会报错。"
)

st.markdown("**完整用法示例（你本地有视频文件时可以直接用）：**")
st.code(
    '''# ① 本地文件路径
st.video("video.mp4")

# ② 网络视频地址（需要联网）
st.video("https://www.w3schools.com/html/mov_bbb.mp4")

# ③ 传字节串（从数据库 / 上传组件拿到的二进制内容）
uploaded = st.file_uploader("上传视频", type=["mp4", "webm", "mov"])
if uploaded is not None:
    st.video(uploaded.read(), format="video/mp4")

# ④ 从第 10 秒开始播，只播到第 30 秒
st.video("video.mp4", start_time=10, end_time=30)

# ⑤ 静音 + 自动播放 + 循环（做背景视频）
st.video("loop.mp4", autoplay=True, muted=True, loop=True)

# ⑥ 带字幕（需要准备一个 .vtt 文件）
st.video("lesson.mp4", subtitles="lesson.zh.vtt")''',
    language="python",
)

st.info(
    "**支持的视频格式：**MP4（H.264）兼容性最好；WebM 在 Chrome/Firefox 上支持良好；"
    "`st.video` 底层用的是 HTML5 `<video>` 标签，**能不能播最终取决于浏览器**。"
)

st.divider()

# ---------------------------------------------------------------------------
# 四、课案原文的完整示例 + 与本文件的差异
# ---------------------------------------------------------------------------
st.header("四、课案原文的示例（对比说明）")
st.code(
    '''import streamlit as st
from PIL import Image

st.subheader("显示图片")
st.image("https://www.python.org/static/img/python-logo.png", caption="Python Logo", width=300)

st.subheader("本地图片")
img = Image.open("photo.png")
st.image(img, caption="本地照片")

st.subheader("视频")
st.video("https://www.w3schools.com/html/mov_bbb.mp4")''',
    language="python",
)

st.markdown(
    """
**课案这段代码的三个"前提"：**

1. `st.image("https://...")` 需要**联网**；
2. `Image.open("photo.png")` 要求**当前目录下真的有 photo.png**，
   否则会抛 `FileNotFoundError`；
3. `st.video("https://...")` 同样需要**联网**。

**本文件的做法：**把这三件事分别替换成 ——

| 课案写法 | 本文件的做法 | 理由 |
|---|---|---|
| `st.image("https://...")` | 用 Pillow 生成图片再展示 | 不需要网络，且能演示 Pillow |
| `Image.open("photo.png")` | 生成后保存成真实 PNG，再用路径和 PIL 对象两种方式展示 | 文件**确实存在**，不会报错 |
| `st.video("https://...")` | 只用注释说明用法 | 不引入运行时依赖，绝不报错 |

> **一条实战经验：**凡是"读取文件"的代码，都要先确认文件真的存在。
> 稳妥的写法是先判断再读：
> ```python
> if Path("photo.png").exists():
>     st.image(Image.open("photo.png"))
> else:
>     st.info("请先把 photo.png 放到脚本同目录下")
> ```
"""
)

# 现场演示这种"先判断再读"的写法（故意用一个不存在的文件，但页面不会报错）
st.markdown("**「先判断再读」的现场演示**（故意指向一个不存在的文件）：")
missing_file = MEDIA_DIR / "这个文件并不存在.png"
if missing_file.exists():
    st.image(str(missing_file))
else:
    st.info(
        f"文件 `{missing_file.name}` 不存在，所以这里显示提示而不是报错。"
        "—— 这就是健壮代码和脆弱代码的区别。"
    )

st.divider()

st.success(
    "**本节要点回顾：**\n"
    "1. `st.image` 接受**路径 / URL / PIL.Image / numpy 数组**四种输入，前两种需要文件真实存在。\n"
    "2. `st.audio` 接受**路径 / URL / bytes / numpy 数组**；传数组时必须给 `sample_rate`。\n"
    "3. `st.video` 的用法与 `st.audio` 对称，底层是 HTML5 `<video>`，格式支持取决于浏览器。\n"
    "4. **生成素材 > 依赖素材**：用代码生成图片/音频，能让示例在任何环境下都不会出错。\n"
    "5. 读文件前先 `Path(...).exists()` 判断一下，是让程序健壮的最简单技巧。"
)
